create table if not exists audit_log (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('create', 'update', 'delete', 'upload')),
  module text not null,
  record_key text not null default '-',
  summary text not null default '',
  actor_id uuid references auth.users(id),
  actor_name text not null default 'Sistema',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table audit_log enable row level security;

drop policy if exists "audit_log_read_admin_direction" on audit_log;
drop policy if exists "audit_log_insert_authenticated" on audit_log;

create policy "audit_log_read_admin_direction"
on audit_log
for select
using (public.current_role() in ('admin', 'direccion'));

create policy "audit_log_insert_authenticated"
on audit_log
for insert
with check (auth.uid() is not null);
