create table if not exists document_files (
  id bigint generated by default as identity primary key,
  kind text not null default 'Otro',
  related_type text not null default 'General',
  related_number text not null default '-',
  name text not null,
  mime_type text not null default 'application/octet-stream',
  size_bytes bigint not null default 0,
  storage_path text not null,
  public_url text,
  notes text not null default '',
  uploaded_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table document_files enable row level security;

insert into storage.buckets (id, name, public)
values ('erp-documents', 'erp-documents', false)
on conflict (id) do nothing;

drop policy if exists "document_files_read_by_role" on document_files;
drop policy if exists "document_files_insert_by_role" on document_files;
drop policy if exists "document_files_update_by_role" on document_files;
drop policy if exists "document_files_delete_by_role" on document_files;

create policy "document_files_read_by_role"
on document_files
for select
using (public.can_read_module('document_files'));

create policy "document_files_insert_by_role"
on document_files
for insert
with check (public.can_write_module('document_files'));

create policy "document_files_update_by_role"
on document_files
for update
using (public.can_write_module('document_files'))
with check (public.can_write_module('document_files'));

create policy "document_files_delete_by_role"
on document_files
for delete
using (public.can_write_module('document_files'));

drop policy if exists "erp_documents_storage_read" on storage.objects;
drop policy if exists "erp_documents_storage_insert" on storage.objects;
drop policy if exists "erp_documents_storage_update" on storage.objects;
drop policy if exists "erp_documents_storage_delete" on storage.objects;

create policy "erp_documents_storage_read"
on storage.objects
for select
using (bucket_id = 'erp-documents' and public.can_read_module('document_files'));

create policy "erp_documents_storage_insert"
on storage.objects
for insert
with check (bucket_id = 'erp-documents' and public.can_write_module('document_files'));

create policy "erp_documents_storage_update"
on storage.objects
for update
using (bucket_id = 'erp-documents' and public.can_write_module('document_files'))
with check (bucket_id = 'erp-documents' and public.can_write_module('document_files'));

create policy "erp_documents_storage_delete"
on storage.objects
for delete
using (bucket_id = 'erp-documents' and public.can_write_module('document_files'));
