create table if not exists companies (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null default 'General',
  city text not null default 'Neuquen',
  status text not null default 'Prospecto',
  contact text not null default 'Sin asignar',
  phone text not null default '-',
  next_action text not null default 'Primer contacto',
  value numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists opportunities (
  id bigint generated by default as identity primary key,
  company text not null,
  service text not null,
  stage text not null default 'Nuevo prospecto',
  amount numeric(14,2) not null default 0,
  probability integer not null default 20 check (probability between 0 and 100),
  owner text not null default 'Ventas',
  due date,
  created_at timestamptz not null default now()
);

create table if not exists quotes (
  number text primary key,
  client text not null,
  service text not null,
  subtotal numeric(14,2) not null default 0,
  tax numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  status text not null default 'Borrador',
  valid_until date,
  created_at timestamptz not null default now()
);

create table if not exists work_orders (
  number text primary key,
  client text not null,
  service text not null,
  status text not null default 'Pendiente',
  progress integer not null default 0 check (progress between 0 and 100),
  margin numeric(5,2) not null default 0,
  start_date date,
  end_date date,
  team text not null default 'Sin asignar',
  created_at timestamptz not null default now()
);

create table if not exists inventory_items (
  sku text primary key,
  name text not null,
  category text not null default 'General',
  stock numeric(14,2) not null default 0,
  min_stock numeric(14,2) not null default 0,
  unit text not null default 'unidades',
  cost numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists purchase_orders (
  number text primary key,
  supplier text not null,
  area text not null default 'General',
  total numeric(14,2) not null default 0,
  status text not null default 'Pendiente',
  due date,
  created_at timestamptz not null default now()
);

create table if not exists invoices (
  number text primary key,
  client text not null,
  concept text not null,
  total numeric(14,2) not null default 0,
  status text not null default 'Pendiente',
  due date,
  created_at timestamptz not null default now()
);

create table if not exists employees (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null default 'Sin rol',
  team text not null default 'Sin asignar',
  status text not null default 'Disponible',
  hours numeric(8,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  text text not null,
  owner text not null default 'General',
  priority text not null default 'Media',
  due date,
  created_at timestamptz not null default now()
);

alter table companies enable row level security;
alter table opportunities enable row level security;
alter table quotes enable row level security;
alter table work_orders enable row level security;
alter table inventory_items enable row level security;
alter table purchase_orders enable row level security;
alter table invoices enable row level security;
alter table employees enable row level security;
alter table tasks enable row level security;

create policy "erp_mvp_read_companies" on companies for select using (true);
create policy "erp_mvp_write_companies" on companies for insert with check (true);
create policy "erp_mvp_update_companies" on companies for update using (true);

create policy "erp_mvp_read_opportunities" on opportunities for select using (true);
create policy "erp_mvp_write_opportunities" on opportunities for insert with check (true);
create policy "erp_mvp_update_opportunities" on opportunities for update using (true);

create policy "erp_mvp_read_quotes" on quotes for select using (true);
create policy "erp_mvp_write_quotes" on quotes for insert with check (true);
create policy "erp_mvp_update_quotes" on quotes for update using (true);

create policy "erp_mvp_read_work_orders" on work_orders for select using (true);
create policy "erp_mvp_write_work_orders" on work_orders for insert with check (true);
create policy "erp_mvp_update_work_orders" on work_orders for update using (true);

create policy "erp_mvp_read_inventory_items" on inventory_items for select using (true);
create policy "erp_mvp_write_inventory_items" on inventory_items for insert with check (true);
create policy "erp_mvp_update_inventory_items" on inventory_items for update using (true);

create policy "erp_mvp_read_purchase_orders" on purchase_orders for select using (true);
create policy "erp_mvp_write_purchase_orders" on purchase_orders for insert with check (true);
create policy "erp_mvp_update_purchase_orders" on purchase_orders for update using (true);

create policy "erp_mvp_read_invoices" on invoices for select using (true);
create policy "erp_mvp_write_invoices" on invoices for insert with check (true);
create policy "erp_mvp_update_invoices" on invoices for update using (true);

create policy "erp_mvp_read_employees" on employees for select using (true);
create policy "erp_mvp_write_employees" on employees for insert with check (true);
create policy "erp_mvp_update_employees" on employees for update using (true);

create policy "erp_mvp_read_tasks" on tasks for select using (true);
create policy "erp_mvp_write_tasks" on tasks for insert with check (true);
create policy "erp_mvp_update_tasks" on tasks for update using (true);
