create table if not exists companies (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null default 'General',
  city text not null default 'Neuquen',
  status text not null default 'Prospecto',
  contact text not null default 'Sin asignar',
  phone text not null default '-',
  contacts jsonb not null default '[]'::jsonb,
  next_action text not null default 'Primer contacto',
  value numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists companies_name_unique on companies (name);

create table if not exists opportunities (
  id bigint generated by default as identity primary key,
  company text not null,
  service text not null,
  stage text not null default 'Nuevo prospecto',
  amount numeric(14,2) not null default 0,
  probability integer not null default 20 check (probability between 0 and 100),
  owner text not null default 'Ventas',
  due date,
  created_at timestamptz not null default now()
);

create unique index if not exists opportunities_company_service_unique on opportunities (company, service);

create table if not exists quotes (
  number text primary key,
  client text not null,
  service text not null,
  subtotal numeric(14,2) not null default 0,
  tax numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  status text not null default 'Borrador',
  valid_until date,
  line_items jsonb not null default '[]'::jsonb,
  client_details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists work_orders (
  number text primary key,
  client text not null,
  service text not null,
  status text not null default 'Pendiente',
  progress integer not null default 0 check (progress between 0 and 100),
  margin numeric(5,2) not null default 0,
  start_date date,
  end_date date,
  team text not null default 'Sin asignar',
  created_at timestamptz not null default now()
);

create table if not exists inventory_items (
  sku text primary key,
  name text not null,
  category text not null default 'General',
  stock numeric(14,2) not null default 0,
  min_stock numeric(14,2) not null default 0,
  unit text not null default 'unidades',
  cost numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists purchase_orders (
  number text primary key,
  supplier text not null,
  area text not null default 'General',
  total numeric(14,2) not null default 0,
  status text not null default 'Pendiente',
  due date,
  created_at timestamptz not null default now()
);

create table if not exists invoices (
  number text primary key,
  client text not null,
  concept text not null,
  total numeric(14,2) not null default 0,
  status text not null default 'Pendiente',
  due date,
  created_at timestamptz not null default now()
);

create table if not exists employees (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null default 'Sin rol',
  team text not null default 'Sin asignar',
  status text not null default 'Disponible',
  hours numeric(8,2) not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists employees_name_unique on employees (name);

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  text text not null,
  owner text not null default 'General',
  priority text not null default 'Media',
  due date,
  created_at timestamptz not null default now()
);

create unique index if not exists tasks_text_owner_due_unique on tasks (text, owner, due);

alter table companies enable row level security;
alter table opportunities enable row level security;
alter table quotes enable row level security;
alter table work_orders enable row level security;
alter table inventory_items enable row level security;
alter table purchase_orders enable row level security;
alter table invoices enable row level security;
alter table employees enable row level security;
alter table tasks enable row level security;

-- RLS policies are defined in database/auth_policies.sql.
-- Do not add permissive MVP policies here; a standalone schema load must stay closed by default.
