-- Bizon ERP production schema
-- Generated from database/*.sql.


-- Source: database\schema.sql

create table if not exists companies (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null default 'General',
  city text not null default 'Neuquen',
  status text not null default 'Prospecto',
  contact text not null default 'Sin asignar',
  phone text not null default '-',
  next_action text not null default 'Primer contacto',
  value numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists companies_name_unique on companies (name);

create table if not exists opportunities (
  id bigint generated by default as identity primary key,
  company text not null,
  service text not null,
  stage text not null default 'Nuevo prospecto',
  amount numeric(14,2) not null default 0,
  probability integer not null default 20 check (probability between 0 and 100),
  owner text not null default 'Ventas',
  due date,
  created_at timestamptz not null default now()
);

create unique index if not exists opportunities_company_service_unique on opportunities (company, service);

create table if not exists quotes (
  number text primary key,
  client text not null,
  service text not null,
  subtotal numeric(14,2) not null default 0,
  tax numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  status text not null default 'Borrador',
  valid_until date,
  created_at timestamptz not null default now()
);

create table if not exists work_orders (
  number text primary key,
  client text not null,
  service text not null,
  status text not null default 'Pendiente',
  progress integer not null default 0 check (progress between 0 and 100),
  margin numeric(5,2) not null default 0,
  start_date date,
  end_date date,
  team text not null default 'Sin asignar',
  created_at timestamptz not null default now()
);

create table if not exists inventory_items (
  sku text primary key,
  name text not null,
  category text not null default 'General',
  stock numeric(14,2) not null default 0,
  min_stock numeric(14,2) not null default 0,
  unit text not null default 'unidades',
  cost numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists purchase_orders (
  number text primary key,
  supplier text not null,
  area text not null default 'General',
  total numeric(14,2) not null default 0,
  status text not null default 'Pendiente',
  due date,
  created_at timestamptz not null default now()
);

create table if not exists invoices (
  number text primary key,
  client text not null,
  concept text not null,
  total numeric(14,2) not null default 0,
  status text not null default 'Pendiente',
  due date,
  created_at timestamptz not null default now()
);

create table if not exists employees (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null default 'Sin rol',
  team text not null default 'Sin asignar',
  status text not null default 'Disponible',
  hours numeric(8,2) not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists employees_name_unique on employees (name);

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  text text not null,
  owner text not null default 'General',
  priority text not null default 'Media',
  due date,
  created_at timestamptz not null default now()
);

create unique index if not exists tasks_text_owner_due_unique on tasks (text, owner, due);

alter table companies enable row level security;
alter table opportunities enable row level security;
alter table quotes enable row level security;
alter table work_orders enable row level security;
alter table inventory_items enable row level security;
alter table purchase_orders enable row level security;
alter table invoices enable row level security;
alter table employees enable row level security;
alter table tasks enable row level security;

create policy "erp_mvp_read_companies" on companies for select using (true);
create policy "erp_mvp_write_companies" on companies for insert with check (true);
create policy "erp_mvp_update_companies" on companies for update using (true);

create policy "erp_mvp_read_opportunities" on opportunities for select using (true);
create policy "erp_mvp_write_opportunities" on opportunities for insert with check (true);
create policy "erp_mvp_update_opportunities" on opportunities for update using (true);

create policy "erp_mvp_read_quotes" on quotes for select using (true);
create policy "erp_mvp_write_quotes" on quotes for insert with check (true);
create policy "erp_mvp_update_quotes" on quotes for update using (true);

create policy "erp_mvp_read_work_orders" on work_orders for select using (true);
create policy "erp_mvp_write_work_orders" on work_orders for insert with check (true);
create policy "erp_mvp_update_work_orders" on work_orders for update using (true);

create policy "erp_mvp_read_inventory_items" on inventory_items for select using (true);
create policy "erp_mvp_write_inventory_items" on inventory_items for insert with check (true);
create policy "erp_mvp_update_inventory_items" on inventory_items for update using (true);

create policy "erp_mvp_read_purchase_orders" on purchase_orders for select using (true);
create policy "erp_mvp_write_purchase_orders" on purchase_orders for insert with check (true);
create policy "erp_mvp_update_purchase_orders" on purchase_orders for update using (true);

create policy "erp_mvp_read_invoices" on invoices for select using (true);
create policy "erp_mvp_write_invoices" on invoices for insert with check (true);
create policy "erp_mvp_update_invoices" on invoices for update using (true);

create policy "erp_mvp_read_employees" on employees for select using (true);
create policy "erp_mvp_write_employees" on employees for insert with check (true);
create policy "erp_mvp_update_employees" on employees for update using (true);

create policy "erp_mvp_read_tasks" on tasks for select using (true);
create policy "erp_mvp_write_tasks" on tasks for insert with check (true);
create policy "erp_mvp_update_tasks" on tasks for update using (true);

-- Source: database\auth_policies.sql

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default 'Usuario Bizon',
  role text not null default 'ventas' check (role in ('admin', 'direccion', 'ventas', 'operaciones', 'compras', 'finanzas', 'rrhh')),
  created_at timestamptz not null default now()
);

alter table profiles enable row level security;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.email, 'Usuario Bizon'),
    'ventas'
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.current_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.can_read_module(module text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select case
    when auth.uid() is null then false
    when public.current_role() in ('admin', 'direccion') then true
    when module in ('companies', 'opportunities', 'quotes') and public.current_role() = 'ventas' then true
    when module in ('work_orders', 'inventory_items') and public.current_role() = 'operaciones' then true
    when module in ('inventory_items', 'purchase_orders') and public.current_role() = 'compras' then true
    when module in ('invoices', 'quotes') and public.current_role() = 'finanzas' then true
    when module in ('employees') and public.current_role() = 'rrhh' then true
    when module in ('tasks', 'document_files') then true
    else false
  end;
$$;

create or replace function public.can_write_module(module text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select case
    when auth.uid() is null then false
    when public.current_role() = 'admin' then true
    when module in ('companies', 'opportunities', 'quotes') and public.current_role() = 'ventas' then true
    when module in ('work_orders') and public.current_role() = 'operaciones' then true
    when module in ('inventory_items', 'purchase_orders') and public.current_role() = 'compras' then true
    when module in ('invoices') and public.current_role() = 'finanzas' then true
    when module in ('employees') and public.current_role() = 'rrhh' then true
    when module in ('tasks', 'document_files') then true
    else false
  end;
$$;

drop policy if exists "erp_mvp_read_companies" on companies;
drop policy if exists "erp_mvp_write_companies" on companies;
drop policy if exists "erp_mvp_update_companies" on companies;
drop policy if exists "erp_mvp_read_opportunities" on opportunities;
drop policy if exists "erp_mvp_write_opportunities" on opportunities;
drop policy if exists "erp_mvp_update_opportunities" on opportunities;
drop policy if exists "erp_mvp_read_quotes" on quotes;
drop policy if exists "erp_mvp_write_quotes" on quotes;
drop policy if exists "erp_mvp_update_quotes" on quotes;
drop policy if exists "erp_mvp_read_work_orders" on work_orders;
drop policy if exists "erp_mvp_write_work_orders" on work_orders;
drop policy if exists "erp_mvp_update_work_orders" on work_orders;
drop policy if exists "erp_mvp_read_inventory_items" on inventory_items;
drop policy if exists "erp_mvp_write_inventory_items" on inventory_items;
drop policy if exists "erp_mvp_update_inventory_items" on inventory_items;
drop policy if exists "erp_mvp_read_purchase_orders" on purchase_orders;
drop policy if exists "erp_mvp_write_purchase_orders" on purchase_orders;
drop policy if exists "erp_mvp_update_purchase_orders" on purchase_orders;
drop policy if exists "erp_mvp_read_invoices" on invoices;
drop policy if exists "erp_mvp_write_invoices" on invoices;
drop policy if exists "erp_mvp_update_invoices" on invoices;
drop policy if exists "erp_mvp_read_employees" on employees;
drop policy if exists "erp_mvp_write_employees" on employees;
drop policy if exists "erp_mvp_update_employees" on employees;
drop policy if exists "erp_mvp_read_tasks" on tasks;
drop policy if exists "erp_mvp_write_tasks" on tasks;
drop policy if exists "erp_mvp_update_tasks" on tasks;

drop policy if exists "profiles_read_self" on profiles;
drop policy if exists "profiles_update_admin" on profiles;
drop policy if exists "companies_read_by_role" on companies;
drop policy if exists "companies_insert_by_role" on companies;
drop policy if exists "companies_update_by_role" on companies;
drop policy if exists "companies_delete_by_role" on companies;
drop policy if exists "opportunities_read_by_role" on opportunities;
drop policy if exists "opportunities_insert_by_role" on opportunities;
drop policy if exists "opportunities_update_by_role" on opportunities;
drop policy if exists "opportunities_delete_by_role" on opportunities;
drop policy if exists "quotes_read_by_role" on quotes;
drop policy if exists "quotes_insert_by_role" on quotes;
drop policy if exists "quotes_update_by_role" on quotes;
drop policy if exists "quotes_delete_by_role" on quotes;
drop policy if exists "work_orders_read_by_role" on work_orders;
drop policy if exists "work_orders_insert_by_role" on work_orders;
drop policy if exists "work_orders_update_by_role" on work_orders;
drop policy if exists "work_orders_delete_by_role" on work_orders;
drop policy if exists "inventory_items_read_by_role" on inventory_items;
drop policy if exists "inventory_items_insert_by_role" on inventory_items;
drop policy if exists "inventory_items_update_by_role" on inventory_items;
drop policy if exists "inventory_items_delete_by_role" on inventory_items;
drop policy if exists "purchase_orders_read_by_role" on purchase_orders;
drop policy if exists "purchase_orders_insert_by_role" on purchase_orders;
drop policy if exists "purchase_orders_update_by_role" on purchase_orders;
drop policy if exists "purchase_orders_delete_by_role" on purchase_orders;
drop policy if exists "invoices_read_by_role" on invoices;
drop policy if exists "invoices_insert_by_role" on invoices;
drop policy if exists "invoices_update_by_role" on invoices;
drop policy if exists "invoices_delete_by_role" on invoices;
drop policy if exists "employees_read_by_role" on employees;
drop policy if exists "employees_insert_by_role" on employees;
drop policy if exists "employees_update_by_role" on employees;
drop policy if exists "employees_delete_by_role" on employees;
drop policy if exists "tasks_read_by_role" on tasks;
drop policy if exists "tasks_insert_by_role" on tasks;
drop policy if exists "tasks_update_by_role" on tasks;
drop policy if exists "tasks_delete_by_role" on tasks;

create policy "profiles_read_self" on profiles for select using (auth.uid() = id or public.current_role() in ('admin', 'direccion'));
create policy "profiles_update_admin" on profiles for update using (public.current_role() = 'admin') with check (public.current_role() = 'admin');

create policy "companies_read_by_role" on companies for select using (public.can_read_module('companies'));
create policy "companies_insert_by_role" on companies for insert with check (public.can_write_module('companies'));
create policy "companies_update_by_role" on companies for update using (public.can_write_module('companies')) with check (public.can_write_module('companies'));
create policy "companies_delete_by_role" on companies for delete using (public.can_write_module('companies'));

create policy "opportunities_read_by_role" on opportunities for select using (public.can_read_module('opportunities'));
create policy "opportunities_insert_by_role" on opportunities for insert with check (public.can_write_module('opportunities'));
create policy "opportunities_update_by_role" on opportunities for update using (public.can_write_module('opportunities')) with check (public.can_write_module('opportunities'));
create policy "opportunities_delete_by_role" on opportunities for delete using (public.can_write_module('opportunities'));

create policy "quotes_read_by_role" on quotes for select using (public.can_read_module('quotes'));
create policy "quotes_insert_by_role" on quotes for insert with check (public.can_write_module('quotes'));
create policy "quotes_update_by_role" on quotes for update using (public.can_write_module('quotes')) with check (public.can_write_module('quotes'));
create policy "quotes_delete_by_role" on quotes for delete using (public.can_write_module('quotes'));

create policy "work_orders_read_by_role" on work_orders for select using (public.can_read_module('work_orders'));
create policy "work_orders_insert_by_role" on work_orders for insert with check (public.can_write_module('work_orders'));
create policy "work_orders_update_by_role" on work_orders for update using (public.can_write_module('work_orders')) with check (public.can_write_module('work_orders'));
create policy "work_orders_delete_by_role" on work_orders for delete using (public.can_write_module('work_orders'));

create policy "inventory_items_read_by_role" on inventory_items for select using (public.can_read_module('inventory_items'));
create policy "inventory_items_insert_by_role" on inventory_items for insert with check (public.can_write_module('inventory_items'));
create policy "inventory_items_update_by_role" on inventory_items for update using (public.can_write_module('inventory_items')) with check (public.can_write_module('inventory_items'));
create policy "inventory_items_delete_by_role" on inventory_items for delete using (public.can_write_module('inventory_items'));

create policy "purchase_orders_read_by_role" on purchase_orders for select using (public.can_read_module('purchase_orders'));
create policy "purchase_orders_insert_by_role" on purchase_orders for insert with check (public.can_write_module('purchase_orders'));
create policy "purchase_orders_update_by_role" on purchase_orders for update using (public.can_write_module('purchase_orders')) with check (public.can_write_module('purchase_orders'));
create policy "purchase_orders_delete_by_role" on purchase_orders for delete using (public.can_write_module('purchase_orders'));

create policy "invoices_read_by_role" on invoices for select using (public.can_read_module('invoices'));
create policy "invoices_insert_by_role" on invoices for insert with check (public.can_write_module('invoices'));
create policy "invoices_update_by_role" on invoices for update using (public.can_write_module('invoices')) with check (public.can_write_module('invoices'));
create policy "invoices_delete_by_role" on invoices for delete using (public.can_write_module('invoices'));

create policy "employees_read_by_role" on employees for select using (public.can_read_module('employees'));
create policy "employees_insert_by_role" on employees for insert with check (public.can_write_module('employees'));
create policy "employees_update_by_role" on employees for update using (public.can_write_module('employees')) with check (public.can_write_module('employees'));
create policy "employees_delete_by_role" on employees for delete using (public.can_write_module('employees'));

create policy "tasks_read_by_role" on tasks for select using (public.can_read_module('tasks'));
create policy "tasks_insert_by_role" on tasks for insert with check (public.can_write_module('tasks'));
create policy "tasks_update_by_role" on tasks for update using (public.can_write_module('tasks')) with check (public.can_write_module('tasks'));
create policy "tasks_delete_by_role" on tasks for delete using (public.can_write_module('tasks'));

-- Source: database\numbering.sql

create table if not exists document_counters (
  code text primary key,
  prefix text not null,
  next_value integer not null default 1 check (next_value > 0),
  padding integer not null default 4 check (padding between 1 and 10),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into document_counters (code, prefix, next_value, padding) values
('quote', 'P', 4, 4),
('work_order', 'OT', 5, 4),
('purchase_order', 'OC', 44, 4),
('invoice', 'F', 87, 5)
on conflict (code) do nothing;

create or replace function public.next_document_number(counter_code text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  current_counter document_counters%rowtype;
  generated_number text;
begin
  select *
  into current_counter
  from document_counters
  where code = counter_code
  for update;

  if not found then
    raise exception 'Unknown counter code: %', counter_code;
  end if;

  generated_number := current_counter.prefix || '-' || lpad(current_counter.next_value::text, current_counter.padding, '0');

  update document_counters
  set next_value = next_value + 1,
      updated_at = now()
  where code = counter_code;

  return generated_number;
end;
$$;

alter table document_counters enable row level security;

drop policy if exists "document_counters_read_admin" on document_counters;
create policy "document_counters_read_admin"
on document_counters
for select
using (public.current_role() in ('admin', 'direccion'));

-- Source: database\documents.sql

create table if not exists document_files (
  id bigint generated by default as identity primary key,
  kind text not null default 'Otro',
  related_type text not null default 'General',
  related_number text not null default '-',
  name text not null,
  mime_type text not null default 'application/octet-stream',
  size_bytes bigint not null default 0,
  storage_path text not null,
  public_url text,
  notes text not null default '',
  uploaded_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table document_files enable row level security;

insert into storage.buckets (id, name, public)
values ('erp-documents', 'erp-documents', false)
on conflict (id) do nothing;

drop policy if exists "document_files_read_by_role" on document_files;
drop policy if exists "document_files_insert_by_role" on document_files;
drop policy if exists "document_files_update_by_role" on document_files;
drop policy if exists "document_files_delete_by_role" on document_files;

create policy "document_files_read_by_role"
on document_files
for select
using (public.can_read_module('document_files'));

create policy "document_files_insert_by_role"
on document_files
for insert
with check (public.can_write_module('document_files'));

create policy "document_files_update_by_role"
on document_files
for update
using (public.can_write_module('document_files'))
with check (public.can_write_module('document_files'));

create policy "document_files_delete_by_role"
on document_files
for delete
using (public.can_write_module('document_files'));

drop policy if exists "erp_documents_storage_read" on storage.objects;
drop policy if exists "erp_documents_storage_insert" on storage.objects;
drop policy if exists "erp_documents_storage_update" on storage.objects;
drop policy if exists "erp_documents_storage_delete" on storage.objects;

create policy "erp_documents_storage_read"
on storage.objects
for select
using (bucket_id = 'erp-documents' and public.can_read_module('document_files'));

create policy "erp_documents_storage_insert"
on storage.objects
for insert
with check (bucket_id = 'erp-documents' and public.can_write_module('document_files'));

create policy "erp_documents_storage_update"
on storage.objects
for update
using (bucket_id = 'erp-documents' and public.can_write_module('document_files'))
with check (bucket_id = 'erp-documents' and public.can_write_module('document_files'));

create policy "erp_documents_storage_delete"
on storage.objects
for delete
using (bucket_id = 'erp-documents' and public.can_write_module('document_files'));

-- Source: database\audit.sql

create table if not exists audit_log (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('create', 'update', 'delete', 'upload')),
  module text not null,
  record_key text not null default '-',
  summary text not null default '',
  actor_id uuid references auth.users(id),
  actor_name text not null default 'Sistema',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table audit_log enable row level security;

drop policy if exists "audit_log_read_admin_direction" on audit_log;
drop policy if exists "audit_log_insert_authenticated" on audit_log;

create policy "audit_log_read_admin_direction"
on audit_log
for select
using (public.current_role() in ('admin', 'direccion'));

create policy "audit_log_insert_authenticated"
on audit_log
for insert
with check (auth.uid() is not null);

-- Source: database\calendar.sql

alter table tasks
add column if not exists event_type text not null default 'Tarea',
add column if not exists start_time time,
add column if not exists end_time time,
add column if not exists notes text not null default '';

-- Source: database\pricing.sql

create table if not exists material_price_catalog (
  id text primary key,
  source text not null,
  category text not null,
  name text not null,
  spec text not null default '',
  unit text not null default 'u',
  length_m numeric(12,2),
  list_price numeric(14,2),
  transfer_price numeric(14,2),
  base_price numeric(14,2) not null default 0,
  price_per_meter numeric(14,2),
  provider text not null default 'Sin proveedor',
  price_date date,
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists labor_rate_catalog (
  id text primary key,
  trade text not null,
  agreement text not null default '',
  category text not null default '',
  base_hour numeric(14,2) not null default 0,
  monthly_bonus numeric(14,2) not null default 0,
  monthly_hours numeric(8,2) not null default 176,
  load_factor numeric(8,4) not null default 0,
  quote_hour numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists quote_calculation_profiles (
  id text primary key,
  name text not null,
  iva numeric(8,4) not null default 0.21,
  iibb numeric(8,4) not null default 0.035,
  target_profit numeric(8,4) not null default 0.25,
  admin_overhead numeric(8,4) not null default 0.10,
  technical_contingency numeric(8,4) not null default 0.05,
  energy_per_kwh numeric(14,2) not null default 150,
  travel_per_km numeric(14,2) not null default 700,
  round_to numeric(14,2) not null default 1000,
  validity_days integer not null default 7,
  created_at timestamptz not null default now()
);

alter table material_price_catalog enable row level security;
alter table labor_rate_catalog enable row level security;
alter table quote_calculation_profiles enable row level security;

drop policy if exists "material_price_catalog_read_by_role" on material_price_catalog;
drop policy if exists "material_price_catalog_write_admin" on material_price_catalog;
drop policy if exists "labor_rate_catalog_read_by_role" on labor_rate_catalog;
drop policy if exists "labor_rate_catalog_write_admin" on labor_rate_catalog;
drop policy if exists "quote_calculation_profiles_read_by_role" on quote_calculation_profiles;
drop policy if exists "quote_calculation_profiles_write_admin" on quote_calculation_profiles;

create policy "material_price_catalog_read_by_role" on material_price_catalog
for select using (auth.uid() is not null);
create policy "material_price_catalog_write_admin" on material_price_catalog
for all using (public.current_role() in ('admin', 'direccion', 'compras')) with check (public.current_role() in ('admin', 'direccion', 'compras'));

create policy "labor_rate_catalog_read_by_role" on labor_rate_catalog
for select using (auth.uid() is not null);
create policy "labor_rate_catalog_write_admin" on labor_rate_catalog
for all using (public.current_role() in ('admin', 'direccion', 'rrhh')) with check (public.current_role() in ('admin', 'direccion', 'rrhh'));

create policy "quote_calculation_profiles_read_by_role" on quote_calculation_profiles
for select using (auth.uid() is not null);
create policy "quote_calculation_profiles_write_admin" on quote_calculation_profiles
for all using (public.current_role() in ('admin', 'direccion')) with check (public.current_role() in ('admin', 'direccion'));

insert into quote_calculation_profiles (id, name, iva, iibb, target_profit, admin_overhead, technical_contingency, energy_per_kwh, travel_per_km, round_to, validity_days)
values ('bizon-metalurgico-2026-03', 'Bizon metalurgico marzo 2026', 0.21, 0.035, 0.25, 0.10, 0.05, 150, 700, 1000, 7)
on conflict (id) do update set
  name = excluded.name,
  iva = excluded.iva,
  iibb = excluded.iibb,
  target_profit = excluded.target_profit,
  admin_overhead = excluded.admin_overhead,
  technical_contingency = excluded.technical_contingency,
  energy_per_kwh = excluded.energy_per_kwh,
  travel_per_km = excluded.travel_per_km,
  round_to = excluded.round_to,
  validity_days = excluded.validity_days;

insert into labor_rate_catalog (id, trade, agreement, category, base_hour, monthly_bonus, monthly_hours, load_factor, quote_hour)
values
('soldador', 'Soldador', 'UOM CCT 260/75', 'Oficial Multiple / Oficial Superior CNC', 6112.95, 35000, 176, 0.65, 10414.49),
('soldador-especializado', 'Soldador especializado', 'UOM CCT 260/75', 'Oficial Multiple Superior CNC', 6541.35, 35000, 176, 0.65, 11121.35),
('electricista-taller', 'Electricista taller', 'UOM CCT 260/75', 'Oficial', 5675.08, 35000, 176, 0.65, 9692.01),
('electricista-obra', 'Electricista obra', 'UOCRA CCT 76/75', 'Oficial - Lineas e Instalacion', 5113, 134100, 176, 0.65, 9693.64),
('electricista-obra-especializado', 'Electricista obra especializado', 'UOCRA CCT 76/75', 'Oficial Especializado - Lineas e Instalacion', 6279, 147000, 176, 0.65, 11738.48),
('ayudante', 'Ayudante', 'UOM CCT 260/75', 'Medio Oficial', 4796.27, 35000, 176, 0.65, 8241.97)
on conflict (id) do update set quote_hour = excluded.quote_hour, base_hour = excluded.base_hour, monthly_bonus = excluded.monthly_bonus, load_factor = excluded.load_factor;

insert into material_price_catalog (id, source, category, name, spec, unit, length_m, list_price, transfer_price, base_price, price_per_meter, provider, price_date)
values
('nqn-hierro-torsionado-12m', 'Bizon Excel NQN', 'Hierros', 'Hierro torsionado x 12 metros', 'Medidas diam. 6 a diam. 32; precio desde variante minima', 'barra', 12, 6296.13, 5666.52, 5666.52, 472.21, 'Carlos Isla', '2026-04-28'),
('nqn-hierro-liso-12m', 'Bizon Excel NQN', 'Hierros', 'Hierro liso x 12 metros', 'Medidas diam. 6 a diam. 32; precio desde variante minima', 'barra', 12, 6644.23, 5979.81, 5979.81, 498.32, 'Carlos Isla', '2026-04-28'),
('nqn-cano-rectangular-6m', 'Bizon Excel NQN', 'Canos estructurales', 'Cano estructural rectangular x 6 metros', 'Medidas 10x20 a 150x50 mm; esp. 1,25 a 6,35 mm', 'barra', 6, 16676.51, 15008.86, 15008.86, 2501.48, 'Carlos Isla', '2026-04-28'),
('nqn-cano-cuadrado-6m', 'Bizon Excel NQN', 'Canos estructurales', 'Cano estructural cuadrado x 6 metros', 'Medidas 10x10 a 140x140 mm; esp. 0,90 a 6,35 mm', 'barra', 6, 10870.83, 9783.75, 9783.75, 1630.63, 'Carlos Isla', '2026-04-28'),
('nqn-cano-redondo-6m', 'Bizon Excel NQN', 'Canos estructurales', 'Cano estructural redondo x 6 metros', 'Diametros 12,70 a 127,00 mm; esp. 1,25 a 6,35 mm', 'barra', 6, 10989.32, 9890.39, 9890.39, 1648.40, 'Carlos Isla', '2026-04-28'),
('nqn-angulos-6m', 'Bizon Excel NQN', 'Perfiles herrero', 'Angulos', 'Medidas 1/2x1/8 a 4x5/16', 'barra', 6, 16748.92, 15074.03, 15074.03, 2512.34, 'Carlos Isla', '2026-04-28'),
('nqn-planchuela-6m', 'Bizon Excel NQN', 'Perfiles herrero', 'Planchuela', 'Variantes multiples de ancho/espesor', 'barra', 6, 8279.30, 7451.37, 7451.37, 1241.90, 'Carlos Isla', '2026-04-28'),
('nqn-electrodo-conarco-325', 'Bizon Excel NQN', 'Consumibles soldadura', 'Electrodo CONARCO-13 3,25 mm', 'Bolsa/caja x 1 kg', 'kg', null, 17821.13, 16039.02, 16039.02, null, 'Carlos Isla', '2026-04-28'),
('ayc-acero-kg-prom', 'AyC web', 'Aceros referencia', 'ACEROS kg/prom', 'Referencia historica A&C octubre 2022', 'kg', null, 290.50, null, 351.50, null, 'AyC', '2022-10-01'),
('ayc-perfil-c-80', 'AyC web', 'Aceros referencia', 'Perfil C 80 40 15 1,6 x 12', 'Referencia historica A&C octubre 2022', 'un', 12, 7427.05, null, 8986.73, 748.89, 'AyC', '2022-10-01')
on conflict (id) do update set base_price = excluded.base_price, price_date = excluded.price_date, provider = excluded.provider;
